apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: gh200-base
  annotations:
    config.kubernetes.io/local-config: "true"

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/name: gh200-retrieval-router
  app.kubernetes.io/part-of: gh200-system
  app.kubernetes.io/managed-by: kustomize

# Resources to include
resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- rbac.yaml
- statefulset.yaml
- service.yaml
- ingress.yaml
- hpa.yaml

# Images to use
images:
- name: nvcr.io/terragon/gh200-retrieval-router
  newTag: latest

# Configuration transformers
configurations:
- kustomizeconfig.yaml

# Patches
patchesStrategicMerge:
- patches/statefulset-patch.yaml

# Config map generator for dynamic configuration
configMapGenerator:
- name: gh200-runtime-config
  files:
  - config/runtime.yaml
  - config/logging.yaml
  options:
    disableNameSuffixHash: true

# Secret generator for sensitive data
secretGenerator:
- name: gh200-api-keys
  type: Opaque
  options:
    disableNameSuffixHash: true
  literals:
  - api_key=generate-secure-api-key
  - webhook_secret=generate-secure-webhook-secret

# Namespace
namespace: gh200-system

# Name prefix for all resources
namePrefix: ""

# Name suffix for all resources
nameSuffix: ""

# Replica count
replicas:
- name: gh200-retrieval-router
  count: 4